name: daily-fetch
on:
  schedule:
    - cron: '0 7'  # 每天 15:00 BJT（07:00 UTC）
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: true }
      - uses: actions/setup-python@v4
        with: { python-version: '3.11' }
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python src/aggregate.py
      - name: Commit data if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv || true
          if ! git diff --staged --quiet; then
            git commit -m "update $(date -u +'%F %T')"
            git push
          else
            echo "no changes"
          fi
